In [1]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("resources/zoo.csv")
dataset.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [2]:
print(type(dataset.iloc[: , 1:17]))

X = dataset.iloc[: , 1:17].values
y = dataset.iloc[: , -1].values

y

<class 'pandas.core.frame.DataFrame'>


array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2, 1,
       2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2, 1, 1,
       7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2, 6, 5, 3, 3,
       4, 1, 1, 2, 1, 6, 1, 7, 2])

In [21]:
X = dataset.iloc[: , 1:17].values
y = dataset.iloc[: , -1].values

# Make number of legs values between 0 & 5
y[:][y[:]==7]=int(0)
X[:,12][X[:,12]==2]=int(1)
X[:,12][X[:,12]==4]=int(2)
X[:,12][X[:,12]==6]=int(3)
X[:,12][X[:,12]==8]=int(4)

y_som = y 

# Categorise leg feature
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X12 = onehotencoder.fit_transform(X[:, 12].reshape(-1, 1)).toarray()
y = onehotencoder.fit_transform(y.reshape(-1,1)).toarray()

print("Shape of X: {}".format(X.shape))
print("Shape of y: {}".format(y.shape))
print("Shape of X12: {}".format(X12.shape))

# Cast as int
y = np.asarray(y, dtype=int)
X12 = np.asarray(X12, dtype=int)

# Replace legs column with encoded legs
Xnew = np.append(X, X12, axis=1)
X = np.delete(Xnew, 12, axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

Shape of X: (101, 16)
Shape of y: (101, 7)
Shape of X12: (101, 6)


In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Using an Artificial Neural Network to categorize the data

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'relu', input_dim = 21))

# Adding the second hidden layer
classifier.add(Dense(units = 21, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 200)

Using TensorFlow backend.
/Users/kch31/anaconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


Epoch 1/200
80/80 [==============================] - 0s - loss: 1.9409 - acc: 0.4625         
Epoch 2/200
80/80 [==============================] - 0s - loss: 1.9304 - acc: 0.4250     
Epoch 3/200
80/80 [==============================] - 0s - loss: 1.9169 - acc: 0.4250     
Epoch 4/200
80/80 [==============================] - 0s - loss: 1.8987 - acc: 0.4250     
Epoch 5/200
80/80 [==============================] - 0s - loss: 1.8746 - acc: 0.4250     
Epoch 6/200
80/80 [==============================] - 0s - loss: 1.8444 - acc: 0.4250     
Epoch 7/200
80/80 [==============================] - 0s - loss: 1.8085 - acc: 0.4250     
Epoch 8/200
80/80 [==============================] - 0s - loss: 1.7688 - acc: 0.4250     
Epoch 9/200
80/80 [==============================] - 0s - loss: 1.7246 - acc: 0.4250     
Epoch 10/200
80/80 [==============================] - 0s - loss: 1.6770 - acc: 0.4250     
Epoch 11/200
80/80 [==============================] - 0s - loss: 1.6274 - acc: 0.4250     
Epoc

80/80 [==============================] - 0s - loss: 0.2443 - acc: 0.9375     
Epoch 92/200
80/80 [==============================] - 0s - loss: 0.2378 - acc: 0.9375     
Epoch 93/200
80/80 [==============================] - 0s - loss: 0.2324 - acc: 0.9375     
Epoch 94/200
80/80 [==============================] - 0s - loss: 0.2265 - acc: 0.9375     
Epoch 95/200
80/80 [==============================] - 0s - loss: 0.2223 - acc: 0.9375     
Epoch 96/200
80/80 [==============================] - 0s - loss: 0.2159 - acc: 0.9250     
Epoch 97/200
80/80 [==============================] - 0s - loss: 0.2128 - acc: 0.9250     
Epoch 98/200
80/80 [==============================] - 0s - loss: 0.2061 - acc: 0.9250     
Epoch 99/200
80/80 [==============================] - 0s - loss: 0.2010 - acc: 0.9250     
Epoch 100/200
80/80 [==============================] - 0s - loss: 0.1964 - acc: 0.9250     
Epoch 101/200
80/80 [==============================] - 0s - loss: 0.1935 - acc: 0.9250     
Epoch 102/

80/80 [==============================] - 0s - loss: 0.0514 - acc: 1.0000     
Epoch 180/200
80/80 [==============================] - 0s - loss: 0.0518 - acc: 0.9875     
Epoch 181/200
80/80 [==============================] - 0s - loss: 0.0501 - acc: 0.9875     
Epoch 182/200
80/80 [==============================] - 0s - loss: 0.0517 - acc: 0.9875     
Epoch 183/200
80/80 [==============================] - 0s - loss: 0.0482 - acc: 0.9875     
Epoch 184/200
80/80 [==============================] - 0s - loss: 0.0491 - acc: 0.9875     
Epoch 185/200
80/80 [==============================] - 0s - loss: 0.0469 - acc: 1.0000     
Epoch 186/200
80/80 [==============================] - 0s - loss: 0.0466 - acc: 0.9875     
Epoch 187/200
80/80 [==============================] - 0s - loss: 0.0465 - acc: 0.9875     
Epoch 188/200
80/80 [==============================] - 0s - loss: 0.0462 - acc: 0.9875     
Epoch 189/200
80/80 [==============================] - ETA: 0s - loss: 0.0018 - acc: 1.000 - 0

In [23]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)

y_pred_cat = np.argmax(y_pred, axis=1)
y_pred_test_cat = np.argmax(y_pred_test, axis=1)

y_train_cat = np.argmax(y_train, axis=1)
y_test_cat = np.argmax(y_test, axis=1)

#Making the Confusion Matrix (compares actual values with predictions)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train_cat, y_pred_cat)
cm_test = confusion_matrix(y_test_cat, y_pred_test_cat)

print(cm)
print(cm_test)

[[ 8  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0]
 [ 0  0 16  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  8  0  0]
 [ 0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  6]]
[[2 0 0 0 0 0 0]
 [0 7 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 2]]


In [24]:
cm_count=0
cm_wrong=0
for i in range(len(cm)):
    cm_count += cm[i,i]
    for v in range(len(cm)):
        cm_wrong += cm[i,v]
cm_wrong -= cm_count
    
cm_test_count=0
cm_test_wrong=0
for i in range(len(cm_test)):
    cm_test_count += cm_test[i,i]
    for v in range(len(cm_test)):
        cm_test_wrong += cm_test[i,v]
cm_test_wrong -= cm_test_count

accuracy = cm_count/(cm_count + cm_wrong)
accuracy_test = cm_test_count/(cm_test_count + cm_test_wrong)

print(accuracy)
print(accuracy_test)

# 100% accuracy classifyihng animals in the train and test sets

1.0
0.952380952381
